### PR TITLE
fix: avoid forcing unwanted blank lines

### LINKED ISSUE #94: require CallExpressions inside MemberExpressions trick group-imports rule
Just noticed this while looking at https://github.com/liferay/liferay-js-themes-toolkit/pull/393/files#diff-607f89928a61f2489713663b891f76aa

```diff
diff --git a/packages/liferay-theme-tasks/plugin/test/tasks/version.js b/packages/liferay-theme-tasks/plugin/test/tasks/version.js
index 1ebd412..1634a94 100644
--- a/packages/liferay-theme-tasks/plugin/test/tasks/version.js
+++ b/packages/liferay-theme-tasks/plugin/test/tasks/version.js
@@ -10,6 +10,7 @@ var chai = require('chai');
 var del = require('del');
 var fs = require('fs-extra');
 var Gulp = require('gulp').Gulp;
+
 var os = require('os');
 var path = require('path');

@@ -30,11 +31,11 @@ var initCwd = process.cwd();
 var registerTasks;
 var runSequence;

```

Looks like the `Gulp` require is tricking the group-imports rule into starting a new group.

### PR DESCRIPTION
**Pull request by wincent**
This is a very dumb fix for the two special cases reported in #94. I'd like to find something a little more general and less hard-coded though, but it is late and nothing elegant is occurring to me at this time.

Close: https://github.com/liferay/eslint-config-liferay/issues/94

### CODE REVIEW

**Comment by wincent** [comment]
Draft only for now because this is just part "1." of the fix mentioned [here](https://github.com/liferay/eslint-config-liferay/issues/94#issuecomment-534298401). Would like to do at least "2." as well, and maybe "3.", but probably not a good idea to code while sleepy so I'll look at this tomorrow.

File: plugins/eslint-plugin-liferay/lib/rules/group-imports.js [hunk 1]
```diff
@@ -108,8 +108,22 @@ module.exports = {
...
+							register(node.parent.parent.parent);
+						} else if (node.parent.type === 'ExpressionStatement') {
 							register(node.parent);
+						} else if (
+							node.parent.type === 'MemberExpression' &&
+							node.parent.parent.type === 'VariableDeclarator' &&
+							node.parent.parent.parent.type ===
+								'VariableDeclaration'
+						) {
+							register(node.parent.parent.parent);
```
Comment (wincent) [inline plugins/eslint-plugin-liferay/lib/rules/group-imports.js]: So this whole approach is super manual and special-casey, and note that any such code that I put in here technically should go in `sort-imports` and maybe `imports-first` as well. Will consider ways to do this better tomorrow.

**Comment by wincent** [comment]
Moving this out of draft status. I still am not thrilled about how special casey this all is, but 🤷‍♂ .

Will push separate PR adding the `destructure-requires` rule that is complementary to this one, but is a feature instead of a fix, so needs to be in a separate PR.

**Comment by wincent** [comment]
The separate PR I mentioned is: https://github.com/liferay/eslint-config-liferay/pull/98

**Comment by wincent** [comment]
Going to merge this one otherwise I am going to start having merge conflicts with myself.

**Comment by wincent** [comment]
And (probably) final follow-up PR is up at: https://github.com/liferay/eslint-config-liferay/pull/99
